App/blueprints/auth.py
import os

from flask import Blueprint, redirect, url_for, session, request, render_template, current_app
from flask_login import login_required, current_user, login_user, logout_user

from App.db.models.database import Docenti, Studenti, db, Admin
from App.utils.utilies import check_credentials

auth = Blueprint('auth', __name__)


@auth.route('/')
def home():
    print("sono in home")
    db.session.close()
    current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_UTENTE')
    return render_template('home.html')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if session['user_type'] == Studenti.__name__:
            return redirect(url_for('student.studentPage'))
        if session['user_type'] == Admin.__name__:
            return redirect(url_for('admin.adminPage'))
        elif session['user_type'] == Docenti.__name__:
            return redirect(url_for('teacher.teacherPage'))

    db.session.close()
    current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_UTENTE')
    print(current_app.config['SQLALCHEMY_DATABASE_URI'])
    if request.method == 'POST':
        print("request.form['user']:", request.form['user'])
        pair = check_credentials(request.form['user'], request.form['password'])
        print("pair:", pair)
        if pair[0]:
            print('login success')
            login_user(pair[1])
            db.session.close()
            if session['user_type'] == Studenti.__name__:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_STUDENTE')
                return redirect(url_for('student.studentPage'))
            if session['user_type'] == Admin.__name__:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_ADMIN')
                return redirect(url_for('admin.adminPage'))
            else:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_DOCENTE')
                return redirect(url_for('teacher.teacherPage'))

    print('login failed')
    return render_template('login.html')


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

App/blueprints/student.py
from copy import copy
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, redirect, json, flash, get_flashed_messages
from flask_login import login_required, current_user
from sqlalchemy import select, and_
from sqlalchemy.exc import DatabaseError
from sqlalchemy.orm.sync import update

from App.checkFunctions import checkStudente
from App.db.models.database import Appelli, db, formalizzazioneEsami, iscrizioni, Prove

student = Blueprint('student', __name__, url_prefix='/student', template_folder='templates')


@student.route('/')
@login_required
@checkStudente
def studentPage():
    print("sono in studentPage")
    return render_template('student/home.html', student=current_user)


@student.route('/appelliDisponibili')
@login_required
@checkStudente
def appelliDisponibili():
    #rendere disponibili gli appelli per lo studente che non ha ancora prenotato un appello
    #ma ha la possibilità di iscriversi ad un altro appello relativo ad una prova che ha gia passato, ma con voto non formalizzato
    print("sono in prenotaAppello")
    messaggi = get_flashed_messages()
    appelli_disp = current_user.getAppelliDisponibili()
    appelli_non_validi = current_user.getAppelliNonValidi()
    appelli_a_cui_sei_iscritto = set(current_user.appelli) - set(appelli_non_validi)
    prove_a_cui_sono_iscritto = [appello.prove for appello in appelli_a_cui_sei_iscritto]
    return render_template('student/appelliDisponibili.html', appelli_disponibili=appelli_disp, studente = current_user, prove_a_cui_sono_iscritto = prove_a_cui_sono_iscritto, messaggi = messaggi)



@student.route('/appelliDisponibili/prenota/<codAppello>', methods=['POST', 'GET'])
@login_required
@checkStudente
def prenotaAppello(codAppello):
    try:
        print("sono in prenotaAppello")

        selected_appointment_id = codAppello
        appello = Appelli.query.get(selected_appointment_id)
        current_user.appelli.append(appello)

        # Get the prova (exam) associated with the selected appointment
        selected_appointment = Appelli.query.get(selected_appointment_id)
        selected_prova = selected_appointment.prova

        # Use SQLAlchemy's update method on the Iscrizioni table to set 'isValid' to False for existing appointments
        stmt = iscrizioni.update().where(
            and_(
                iscrizioni.c.studente == current_user.matricola,
                iscrizioni.c.appello != selected_appointment_id,
                iscrizioni.c.appello.in_(
                    select(Appelli.codAppello).where(Appelli.prova == selected_prova)
                )
            )
        ).values(isValid=False)


        #Qui si attiverà il trigger che mettera isValid a False per tutte le altre prove che ne dipendono.


        with db.engine.begin() as connection:
            connection.execute(stmt)

        # Commit the changes to the database
        db.session.commit()

        return redirect(url_for('student.appelliDisponibili'))
    except DatabaseError as e:
        print(e)
        flash('Non puoi iscriverti a questa prova, perche non hai ricevuto nessun voto per la prova precedente')
        return redirect(url_for('student.appelliDisponibili'))




@student.route('/prenotazioni')
@login_required
@checkStudente
def prenotazioni():
    print("sono in prenotazioni")
    print(prenotazioni)
    return render_template('student/prenotazioni.html', studente=current_user, datetime= datetime)


@student.route('/prenotazioni/eliminaPrenotazione/<codAppello>', methods=['POST', 'GET'])
@login_required
@checkStudente
def eliminaPrenotazioneAppello(codAppello):
    print("sono in prenotaAppello")
    appello = Appelli.query.get(codAppello)
    if appello in current_user.appelli:
        current_user.appelli.remove(appello)

    db.session.commit()

    return redirect(url_for('student.prenotazioni'))





@student.route('/pianoDiStudi')
@login_required
@checkStudente
def pianoDiStudi():
    print("sono in EsamiFormalizzati")
    print(current_user.esami)
    #for each element in piano di studi, se formalizzato aggiungi il voto

    return render_template('student/pianoDiStudi.html', studente=current_user)


@student.route('/bachecaEsiti')
@login_required
@checkStudente
def esiti():
    #renderizza la pagina di gestione della formalizzazione
    esami_non_form = current_user.getEsamiNonFormalizzatiandPassati()
    return render_template('student/esiti.html', esami=esami_non_form, student = current_user)


@student.route('/bachecaEsiti/formalizza/<codEsame>', methods=['POST', 'GET'])
@login_required
@checkStudente
def formalizza(codEsame):
    #effettua la formalizzazione vera e propria, conclude con un redirect a esiti.
    esame_cod = codEsame
    current_user.formalizzaEsame(esame_cod)
    return redirect(url_for('student.esiti'))


@student.route('/bachecaEsiti/rifiuta/<codEsame>', methods=['POST', 'GET'])
@login_required
@checkStudente
def rifiuta(codEsame):
    #effettua la formalizzazione vera e propria, conclude con un redirect a esiti.
    esame_cod = codEsame
    # Begin a transaction
    current_user.rifiutaEsame(esame_cod)
    return redirect(url_for('student.esiti'))

App/templates/student/appelliDisponibili.html
<!-- templates/index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='sidebar.css') }}">
    <title>Prenotazioni disponibili per lo studente</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">
    <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</head>
<body>


    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > </a>
        <a href="{{ url_for('student.studentPage') }}" class="navbar-brand">Profilo studente ></a>
        <a href="#" class="navbar-brand">Prenotazioni Appelli</a>
        <a class="navbar-brand ml-auto"> </a>

        <div id="mySidebar" class="sidebar">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{{ url_for('student.appelliDisponibili') }}">Prenota Appello</a>
          <a href="{{ url_for('student.prenotazioni') }}">Prenotazioni</a>
          <a href="{{ url_for('student.pianoDiStudi') }}">Piano di studi</a>
          <a href="{{ url_for('student.esiti') }}">Bacheca Esiti</a>
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <div id="main" style="padding: 0px;">
          <button class="btn btn-info" onclick="openNav()">&#9776; Menu</button>
        </div>
    </nav>

    <div class="p-3 mb-2 m-5  containergrigio">
    <div class="container p-3">

    <h2>Prenotazioni disponibili per lo studente</h2>
    <hr>
       {% if messaggi %}
    <!-- Mostra un alert -->
    <script>
        alert("{{ messaggi[0] }}");
    </script>
        {% endif %}
        <table class="table">
            <thead class="thead bg-info">
                <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Luogo</th>
                    <th scope="col">Prova</th>
                    <th scope="col">Corso Relativo</th>
                    <th scope="col">Prenota</th>
                </tr>
            </thead>
            <tbody>
                {% for appello in studente.getAppelliDisponibiliPossibili() %}
                    <tr>
                        <td>{{ appello.data.strftime('%Y-%m-%d') }}</td>
                        <td>{{ appello.luogo }}</td>
                        <td>{{ appello.prove }}</td>
                        <td>{{ appello.prove.esami }}</td>
                        <td>
                                {% if appello.prove in prove_a_cui_sono_iscritto %}
                                    <a href="{{ url_for('student.prenotaAppello', codAppello=appello.codAppello) }}"
                                       onclick="return confirm('Stai andando ad eliminare un appello che hai già effettuato,' +
                                        ' procedendo con la prenotazione andrai ad invalidare l appello che hai selezionato' +
                                         ' e anche gli eventuali appelli relativi a prove che richiedevano il superamento di una prova' +
                                          ' relativa all appelllo selezionato.' +
                                           ' Sei sicuro di voler effettuare la prenotazione?');">
                                        <button type="submit" class="btn btn-danger">Prenota</button>
                                    </a>
                                {% else %}
                                    <a href="{{ url_for('student.prenotaAppello', codAppello=appello.codAppello) }}">
                                        <button type="submit" class="btn btnteall">Prenota</button>
                                    </a>
                                {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
        <!--<a href="{{ url_for('student.studentPage') }}" class="btn btn-info">
        <i class="fas fa-arrow-left"></i> Torna Indietro
        </a>-->
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

App/templates/student/esiti.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Esiti</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='sidebar.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">
    <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</head>
<body>

    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > </a>
        <a href="{{ url_for('student.studentPage') }}" class="navbar-brand">Profilo studente ></a>
        <a href="#" class="navbar-brand">Bacheca esiti</a>
        <a class="navbar-brand ml-auto"> </a>

        <div id="mySidebar" class="sidebar">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{{ url_for('student.appelliDisponibili') }}">Prenota Appello</a>
          <a href="{{ url_for('student.prenotazioni') }}">Prenotazioni</a>
          <a href="{{ url_for('student.pianoDiStudi') }}">Piano di studi</a>
          <a href="{{ url_for('student.esiti') }}">Bacheca Esiti</a>
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <div id="main" style="padding: 0px;">
          <button class="btn btn-info" onclick="openNav()">&#9776; Menu</button>
        </div>
    </nav>

    <div class="p-3 mb-2 m-5  containergrigio">
    <div class="container p-3">

    <h2>Bacheca esiti</h2>
    <hr>

    <table class="table">
        <thead class="thead bg-info">
            <tr>
                <th scope="col">Esame</th>
                <th scope="col">Voto</th>
                <th scope="col">Lode</th>
                <th scope="col">Formalizza</th>
                <th scope="col">Rifiuta</th>
            </tr>
        </thead>
        <tbody>
            {% for esame in esami %}
                <tr>
                    <td>{{ esame.name }}</td>
                    <td>
                    {% if esame.getVoto(student.matricola) == None %}
                        Non Presente
                    {% elif esame.getVoto(student.matricola) < 18 %}
                        IDONEO
                    {% elif esame.getVoto(student.matricola) > 30 %}
                        30
                    {% else %}
                        {{ esame.getVoto(student.matricola) }}
                    {% endif %}
                    </td>
                    <td>
                            {{ esame.getLode(student.matricola) }}
                    </td>
                    <td>
                            <a href="{{url_for('student.formalizza', codEsame = esame.cod)}}">
                                <button type="submit" class="btn btn-danger">Formalizza</button>
                            </a>
                    </td>
                    <td>
                        <a href="{{url_for('student.rifiuta', codEsame = esame.cod)}}">
                            <button type="submit" class="btn btn-danger">Rifiuta</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    </div>

    <!-- Bootstrap JS and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-Vkoo8x4CGsF3pHJ2+1iRBCEs5Z2AKxyAuvSL9syFiL4U6pV0H+CBKd5im5MlVbB" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyUma1i2D02M7j9i/JXQn5CkMc5NKeZ6I" crossorigin="anonymous"></script>
</body>
</html>

App/templates/student/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Student Homepage</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">
</head>

<body>

    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > Profilo studente
        </a>
    </nav>

    <div class="p-3 mb-2 m-5 containergrigio">
    <div class="container p-3">
        <h2>Benvenuto {{ student.name }}</h2>
        <hr>

        <div class="row p-2 mt-5">
            <div class="col-5"><h5><strong>Informazioni personali:</strong></h5></div>
            <div class="col-7"><h5><strong>Funzionalità:</strong></h5></div>
        </div>
        <div class="row p-2">
        <!-- Use Jinja to dynamically display student information -->
            <div class="col-5"><strong>Nome:</strong> {{ student.name }}</div>
            <div class="col-7">
               <a class="btn btn-outline-danger half-width-btn" href="{{ url_for('student.appelliDisponibili') }}">Prenota Appello</a> </div>
        </div>
        <div class="row p-2">
            <div class="col-5"><strong>Cognome:</strong> {{ student.surname }}</div>
            <div class="col-7">
                 <a class="btn btn-outline-danger half-width-btn" href="{{ url_for('student.prenotazioni') }}">Prenotazioni</a> </div>
        </div>
        <div class="row p-2">
            <div class="col-5"><strong>Media:</strong> {{ student.getMean() }}</div>
            <div class="col-7">
                <a class="btn btn-outline-danger half-width-btn" href="{{ url_for('student.pianoDiStudi') }}">Piano di studi</a> </div>
        </div>

        <div class="row p-2">
            <div class="col-5"></div>
            <div class="col-7">
                <a class="btn btn-outline-danger half-width-btn" href="{{ url_for('student.esiti') }}">Bacheca Esiti</a> </div>
        </div>

        <div class="row p-2">
            <div class="col-5"></div>
            <div class="col-7">
                <a class="btn btn-outline-danger half-width-btn" href="{{ url_for('auth.logout') }}">Logout</a> </div>
        </div>

    </div>
    </div>
    <hr>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.6.0/js/bootstrap.min.js"></script>

</body>

</html>

App/templates/student/pianoDiStudi.html
<!-- templates/index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='sidebar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">
    <title>Esami dello studente</title>
    <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</head>
<body>

    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > </a>
        <a href="{{ url_for('student.studentPage') }}" class="navbar-brand">Profilo studente ></a>
        <a href="#" class="navbar-brand">Piano di studio</a>
        <a class="navbar-brand ml-auto"> </a>

        <div id="mySidebar" class="sidebar">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{{ url_for('student.appelliDisponibili') }}">Prenota Appello</a>
          <a href="{{ url_for('student.prenotazioni') }}">Prenotazioni</a>
          <a href="{{ url_for('student.pianoDiStudi') }}">Piano di studi</a>
          <a href="{{ url_for('student.esiti') }}">Bacheca Esiti</a>
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <div id="main" style="padding: 0px;">
          <button class="btn btn-info" onclick="openNav()">&#9776; Menu</button>
        </div>
    </nav>

    <div class="p-3 mb-2 m-5  containergrigio">
    <div class="container p-3">

    <h2>Piano di studio</h2>
    <hr>
        <table class="table">
            <thead class="bg-info">
                <tr>
                    <th scope="col">Corso</th>
                    <th scope="col">Voto</th>
                    <th scope="col">Lode</th>
                    <th scope="col">CFU</th>
                    <th scope="col">Anno</th>
                </tr>
            </thead>
            <tbody>
                {% for esame in studente.esami %}
                    <tr>
                        <td>{{ esame.name }}</td>
                        <td>
                            {% if esame.getVotoFormalizzato(studente.matricola) == None %}
                            Non ancora sostenuto
                            {% elif esame.getVotoFormalizzato(studente.matricola) == 0 %}
                            IDONEO
                            {% elif esame.getVotoFormalizzato(studente.matricola) > 30 %}
                                    30
                            {% else %}
                                {{ esame.getVotoFormalizzato(studente.matricola) }}
                            {% endif %}
                        </td>
                        <td> {{esame.getLode(studente.matricola) }}</td>
                        <td>{{ esame.cfu }}</td>
                        <td>{{ esame.anno }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

App/templates/student/prenotazioni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='sidebar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">
    <title>Prenotazioni effettuate dallo studente</title>

    <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</head>
<body>

    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > </a>
        <a href="{{ url_for('student.studentPage') }}" class="navbar-brand">Profilo studente ></a>
        <a href="#" class="navbar-brand">Storico prenotazioni</a>
        <a class="navbar-brand ml-auto"> </a>

        <div id="mySidebar" class="sidebar">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{{ url_for('student.appelliDisponibili') }}">Prenota Appello</a>
          <a href="{{ url_for('student.prenotazioni') }}">Prenotazioni</a>
          <a href="{{ url_for('student.pianoDiStudi') }}">Piano di studi</a>
          <a href="{{ url_for('student.esiti') }}">Bacheca Esiti</a>
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <div id="main" style="padding: 0px;">
          <button class="btn btn-info" onclick="openNav()">&#9776; Menu</button>
        </div>
    </nav>

    <div class="p-3 my-2 m-5  containergrigio">
    <div class="container p-3">

    <h2>Prenotazioni effettuate dallo studente</h2>
    <hr>

    <!--<a href="{{ url_for('student.studentPage') }}" class="btn btn-info">
        <i class="fas fa-arrow-left"></i> Torna Indietro
    </a>-->
    <br>
        <table class="table">
            <thead class="bg-info">
                <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Luogo</th>
                    <th scope="col">Prova</th>
                    <th scope="col">Corso Relativo</th>
                    <th scope="col">Stato attività</th>
                    <th scope="col">Voto</th>
                    <th scope="col">Elimina</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="6"><strong>Appelli non più validi</strong></td>
                </tr>
                {% for appello in studente.getAppelliNonValidi() %}
                    <tr>
                        <td>{{ appello.data.strftime('%Y-%m-%d') }}</td>
                        <td>{{ appello.luogo }}</td>
                        <td>{{ appello.prove }}</td>
                        <td>{{ appello.prove.esami }}</td>
                            {% if appello.data < datetime.utcnow() %}
                                <td><button class="btn btn-block btnteall" onclick="mostraData('{{ appello.data }}')">Svolto</button></td>
                            {% else %}
                                <td><button class="btn btn-block btn-danger" >Non Svolto</button></td>
                            {% endif %}
                        <td>{{ studente.getVotoProva(appello.codAppello) }}</td>
                        <td>
                            <a href="{{url_for('student.eliminaPrenotazioneAppello', codAppello=appello.codAppello)}}">
                                <button type="submit" class="btn btn-danger" disabled>Elimina</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tbody>
                <tr>
                    <td colspan="6"><strong>Appelli a cui sei iscritto</strong></td>
                </tr>
                {% for appello in studente.appelli %}
                    {% if appello not in studente.getAppelliNonValidi() %}
                        <tr>
                            <td>{{ appello.data.strftime('%Y-%m-%d') }}</td>
                            <td>{{ appello.luogo }}</td>
                            <td>{{ appello.prove }}</td>
                            <td>{{ appello.prove.esami }}</td>
                            {% if appello.data < datetime.utcnow() %}
                                <td><button class="btn btnteall" onclick="mostraData('{{ appello.data }}')">Svolto</button></td>
                            {% else %}
                                <td><button class="btn btn-danger" >Non Svolto</button></td>
                            {% endif %}
                            <td>{{ studente.getVotoProva(appello.codAppello) }}</td>
                            <td>
                                <a href="{{url_for('student.eliminaPrenotazioneAppello', codAppello=appello.codAppello)}}">
                                    <button type="submit" class="btn btn-danger" >Elimina</button>
                                </a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        function mostraData(data) {
            alert("Hai svolto l'appello in data: " + data);
        }
    </script>
</body>
</html>