App/blueprints/auth.py
import os

from flask import Blueprint, redirect, url_for, session, request, render_template, current_app
from flask_login import login_required, current_user, login_user, logout_user

from App.db.models.database import Docenti, Studenti, db, Admin
from App.utils.utilies import check_credentials

auth = Blueprint('auth', __name__)


@auth.route('/')
def home():
    print("sono in home")
    db.session.close()
    current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_UTENTE')
    return render_template('home.html')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if session['user_type'] == Studenti.__name__:
            return redirect(url_for('student.studentPage'))
        if session['user_type'] == Admin.__name__:
            return redirect(url_for('admin.adminPage'))
        elif session['user_type'] == Docenti.__name__:
            return redirect(url_for('teacher.teacherPage'))

    db.session.close()
    current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_UTENTE')
    print(current_app.config['SQLALCHEMY_DATABASE_URI'])
    if request.method == 'POST':
        print("request.form['user']:", request.form['user'])
        pair = check_credentials(request.form['user'], request.form['password'])
        print("pair:", pair)
        if pair[0]:
            print('login success')
            login_user(pair[1])
            db.session.close()
            if session['user_type'] == Studenti.__name__:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_STUDENTE')
                return redirect(url_for('student.studentPage'))
            if session['user_type'] == Admin.__name__:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_ADMIN')
                return redirect(url_for('admin.adminPage'))
            else:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_DOCENTE')
                return redirect(url_for('teacher.teacherPage'))

    print('login failed')
    return render_template('login.html')


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

App/blueprints/teacher.py
from pytz import UTC

from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import func

from App.checkFunctions import checkDocente
from App.db.models.database import Esami, Prove, db, Appelli, Docenti, iscrizioni, Superamenti, Studenti

teacher = Blueprint('teacher', __name__, url_prefix='/teacher', template_folder='templates')


@teacher.route('/')
@login_required
@checkDocente
def teacherPage():
    print("sono in teacherPage")
    return render_template('teacher/home.html', professore=current_user)


@teacher.route('/visualizzaCorsi')
@login_required
@checkDocente
def visualizzaCorsi():
    #visualizza l'elenco dei corsi tenuti dal professore e le relative prove
    print("sono in visualizzaEsami")
    print(current_user.esami)
    return render_template('teacher/corsi.html', user=current_user, esami=current_user.esami)

@teacher.route('/visualizzaCorsi/visualizzaStudentiInGradoDiFormalizzare/<codEsame>', methods=['GET'])
@login_required
@checkDocente
def visualizzaStudentiInGradoDiFormalizzare(codEsame):
    #visualizza gli studenti che hanno superato tutte le prove di un corso, ma non hanno ancora formalizzato il voto
    print("sono in visualizzaStudentiInGradoDiFormalizzare")
    esame = Esami.query.get(codEsame)
    studenti = esame.getStudentiInGradoDiFormalizzare()
    return render_template('teacher/visualizzaStudentiInGradoDiFormalizzare.html', studenti=studenti, codEsame=codEsame)

@teacher.route('/visualizzaCorsi/visualizzaStudentiInGradoDiFormalizzare/<codEsame>/VisualizzaProve/<matricola>', methods=['GET'])
@login_required
@checkDocente
def visualizzaProveStudente(codEsame, matricola):
    # Ottenere lo studente e le prove relative all'esame
    studente = Studenti.query.filter_by(matricola=matricola).first()
    esame = Esami.query.get(codEsame)
    prove_studente = studente.getProveEsame(codEsame)

    return render_template('teacher/visualizzaProveStudente.html', studente=studente, esame=esame,
                           prove_studente=prove_studente)



@teacher.route('/visualizzaCorsi/visualizzaDocenti/<codEsame>', methods=['GET'])
@login_required
@checkDocente
def visualizzaDocenti(codEsame):
    # Ottieni l'elenco dei docenti relativi all'esame con il codice fornito
    print("sono in visualizzaDocenti")
    print(codEsame)
    docenti = Esami.query.get(codEsame).docenti
    print(docenti)
    # Passa l'elenco dei docenti al template HTML
    return render_template('teacher/visualizzaDocenti.html', docenti=docenti, codEsame=codEsame)


@teacher.route('/visualizzaCorsi/visualizzaDocenti/<codEsame>/ricercaDocente', methods=['GET'])
@login_required
@checkDocente
def ricercaDocente(codEsame):
    # Ottieni l'elenco dei docenti relativi all'esame con il codice fornito
    print("sono in ricercaDocente")
    docenti = Docenti.query.all()
    esame = Esami.query.get(codEsame)
    docenti_relativi_esame = esame.docenti

    return render_template('teacher/ricercaDocente.html', docenti= set(set(docenti) - set(docenti_relativi_esame)),
                           codEsame=codEsame)


@teacher.route('/visualizzaCorsi/visualizzaDocenti/<codEsame>/ricercaDocente/aggiungiDocente/<codDocente>', methods=['POST', 'GET'])
@login_required
@checkDocente
def aggiungiDocente(codEsame, codDocente):
    # Ottieni l'elenco dei docenti relativi all'esame con il codice fornito
    esame = Esami.query.get(codEsame)
    docente = Docenti.query.get(codDocente)
    esame.docenti.append(docente)
    db.session.commit()
    docenti = Esami.query.get(codEsame).docenti

    return redirect(url_for('teacher.visualizzaDocenti', docenti = docenti, codEsame=codEsame))


@teacher.route('/visualizzaCorsi/eliminaProve', methods=['POST', 'GET'])
@login_required
@checkDocente
def eliminaProve():

    return redirect(url_for('teacher.visualizzaEsami'))


@teacher.route('/visualizzaCorsi/visualizzaProve/<codEsame>', methods=['POST', 'GET'])
@login_required
@checkDocente
def visualizzaProve(codEsame):
    #visualizza le prove relative ad un corso
    esame = Esami.query.get(codEsame)
    prove = esame.prove
    esiste_appello_realtivo_all_esame = any(prova.appelli for prova in esame.prove)
    #potrei passare anche un booleano che mi dice se si può creare la prova oppure no
    return render_template('teacher/visualizzaProve.html', user=current_user, prove=prove, esame=esame,
                           lista_prove_abilitate=current_user.prove, codEsame=codEsame,
                           nessun_appello_relativo_all_esame = esiste_appello_realtivo_all_esame)


@teacher.route('/visualizzaCorsi/visualizzaProve/<codEsame>/definisciProva', methods=['POST', 'GET'])
@login_required
@checkDocente
def definisciProva(codEsame):
    #la somma dei pesi delle prove relative a un corso deve fare 1.
    #se il professore non ha ancora creato prove per un corso, deve poterlo fare
    #se il professore ha già creato prove per un corso, deve poterle modificare
    #se il professore ha già creato prove per un corso, deve poterle eliminare
    #non è possibile per problemi di progettazione creare le prove una alla volta, ma solo tutte insieme
    docente = current_user
    esame = Esami.query.get(codEsame)
    prove = esame.prove
    return render_template('teacher/definisciProva.html', user=current_user, prove=prove, codEsame=codEsame)



@teacher.route('/visualizzaCorsi/visualizzaProve/<codEsame>/definisciProve/creaProva', methods=['POST', 'GET'])
@login_required
@checkDocente
def creaProva(codEsame):
    print("sono in creaProva")
    print(request.form)
    codProva = request.form['codProva']
    tipologia = request.form['tipologia']
    peso = request.form['peso']
    bonus = request.form['bonus']
    durata = request.form['durata']
    provePrimarie = request.form.getlist('prove_primarie[]')
    new_prova = Prove(cod=codProva, Tipologia=tipologia, peso=peso, Bonus=bonus, durata=durata, idoneità=True if request.form.get('idoneita') == 'true' else False )


    #richiede il superamento della prova....
    new_superamenti = []
    for provaPrimaria in provePrimarie:
         new_superamenti.append(Superamenti(provaPrimaria=provaPrimaria, provaSuccessiva=codProva))

    #controllare le invariatni....

    esame = Esami.query.get(codEsame)
    esame.prove.append(new_prova)
    current_user.prove.append(new_prova)
    db.session.add(new_prova)
    for superamento in new_superamenti:
        db.session.add(superamento)
    db.session.commit()

    return redirect(url_for('teacher.visualizzaProve', codEsame=codEsame))


@teacher.route('/visualizzaCorsi/visualizzaProve/<codEsame>/eliminaProva/<codProva>', methods=['POST', 'GET'])
@login_required
@checkDocente
def eliminaProva(codEsame, codProva):
    docente = current_user
    prova_to_delete = Prove.query.get(codProva)
    owner_prova = Docenti.query.get(prova_to_delete.docente)
    #Controllo che NON esista nessun appello relativo a nessuna prova relativa al corso.
    esame = Esami.query.get(codEsame)
    esiste_appello_esame = any(prova.appelli for prova in esame.prove)

    if owner_prova == docente and not esiste_appello_esame:
        print("Puoi eliminare questa prova")
        db.session.delete(prova_to_delete)
        db.session.commit()
    else:
        print("Non puoi eliminare questa prova")
    return redirect(url_for('teacher.visualizzaProve', codEsame=codEsame))


@teacher.route('/visualizzaCorsi/visualizzaProve/definisciAppello/<codProva>', methods=['POST', 'GET'])
@login_required
@checkDocente
def definisciAppello(codProva):
    print("sono in definisciAppello")
    isAbilitata = False   #una prova è abilitata quando la somma dei pesi delle prove abilitate per un corso è 1
    prova = Prove.query.get(codProva)
    esame = prova.esami
    codEsame = esame.cod
    pesoTot = 0
    for prova in esame.prove:
        pesoTot = pesoTot + prova.peso
    if pesoTot == 1:
        isAbilitata = True

    if isAbilitata or prova.idoneità == True:
        # crea un appello per una prova
        prova = Prove.query.get(codProva)
        return render_template('teacher/definisciAppello.html', user=current_user, prove=current_user.prove,
                               codEsame = codEsame, codProva=codProva)
    else:
        return redirect(url_for('teacher.visualizzaProve', codEsame=codEsame))


@teacher.route('/visualizzaCorsi/visualizzaProve/definisciAppello/<codProva>/creaAppello', methods=['POST', 'GET'])
@login_required
@checkDocente
def creaAppello(codProva):
    print("sono in creaAppello")
    #crea un appello per una prova
    #impedire la creazione di un appello per una prova il quale appello è definito per una certa distanza di data ?
    #bisognerebbe implementare delle politiche interne.
    prova_id = request.form['prova']
    luogo = request.form['luogo']
    data = request.form['data']
    print("prima di creare l'appello")
    print(Appelli.query.all())
    new_appello = Appelli(data=data, luogo=luogo, prova=codProva)
    db.session.add(new_appello)
    db.session.commit()
    print("dopo aver creato l'appello")
    print(Appelli.query.all())
    return redirect(url_for('teacher.teacherPage'))



#to do da implementare ancora def visualizzaAppelli.
@teacher.route('/visualizzaAppelli')
@login_required
@checkDocente
def visualizzaAppelli():
    print("sono in visualizzaAppelli")
    return render_template('teacher/visualizzaAppelli.html', docente=current_user)


@teacher.route('/visualizzaAppelli/studentiIscritti/<codAppello>', methods=['GET'])
@login_required
@checkDocente
def visualizzaStudentiIscritti(codAppello):
        studenti = Appelli.query.get(codAppello).studenti
        #gli studenti che hanno gia un voto devono comaparire con il voto settato.
        print("sono in visualizzaStudentiIscritti")
        appello = Appelli.query.get(codAppello)
        db_stamp = db.session.query(func.now()).scalar()
        appello_data_aware = appello.data.replace(tzinfo=UTC)

App/templates/teacher/corsi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Esami e Prove</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='sidebar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">
    <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</head>
<body>

    <nav class="navbar navbar-dark bg-info d-flex">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > </a>
        <a href="{{ url_for('teacher.teacherPage') }}" class="navbar-brand">Profilo Insegnante ></a>
        <a href="#" class="navbar-brand">Corsi tenuti</a>
        <a class="navbar-brand ml-auto"> </a>

        <div id="mySidebar" class="sidebar">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{{ url_for('teacher.visualizzaCorsi') }}">Visualizza Corsi</a>
          <a href="{{ url_for('teacher.visualizzaAppelli') }}">Visualizza Appelli</a>
          <a href="{{ url_for('teacher.visualizzaProveGestite') }}">Visualizza Prove Gestite</a>
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <div id="main" style="padding: 0px;">
          <button class="btn btn-info" onclick="openNav()">&#9776; Menu</button>
        </div>
    </nav>

    <div class="p-3 mb-2 m-5  containergrigio">
        <div class="container p-3">

            <h2>Esami e Prove</h2>
            <hr>

            <table class="table">
                <thead class="bg-info">
                    <tr>
                        <th>Esame</th>
                        <th>Prove</th>
                        <th>Visualizza dettagli prove</th>
                        <th>Elenco Docenti</th>
                        <th>Elenco Studenti</th> <!-- Nuova colonna -->
                    </tr>
                </thead>
                <tbody>
                    {% for esame in esami %}
                        <tr>
                            <td>{{ esame.name }}</td>
                            <td>
                                {% for prova in esame.prove %}
                                    {{ prova.cod }}{% if not loop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{{ url_for('teacher.visualizzaProve', codEsame=esame.cod) }}">
                                    <button type="button" class="btn btn-danger">Visualizza dettagli prove</button>
                                </a>
                            </td>
                            <td>
                                <a href="{{ url_for('teacher.visualizzaDocenti', codEsame=esame.cod) }}">
                                    <button type="button" class="btn btn-info">Visualizza Docenti</button>
                                </a>
                            </td>
                            <td>
                                <a href="{{ url_for('teacher.visualizzaStudentiInGradoDiFormalizzare', codEsame=esame.cod) }}">
                                    <button type="button" class="btn btnteall">Visualizza Studenti</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- Altre informazioni dell'utente, se necessario  <p class="mt-3">Benvenuto, {{ user.name }}!</p>-->
        </div>
        </div>

    <!-- Bootstrap JS e le sue dipendenze -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

App/templates/teacher/definisciAppello.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crea Appello</title>
    <!-- Collegamento con Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='sidebar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">

    <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</head>
<body>

    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > </a>
        <a href="{{ url_for('teacher.teacherPage') }}" class="navbar-brand">Profilo Insegnante ></a>
        <a href="{{ url_for('teacher.visualizzaProveGestite') }}" class="navbar-brand">Prove ></a>
        <a href="#" class="navbar-brand">Creazione appello</a>
        <a class="navbar-brand ml-auto"> </a>

        <div id="mySidebar" class="sidebar">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{{ url_for('teacher.visualizzaCorsi') }}">Visualizza Corsi</a>
          <a href="{{ url_for('teacher.visualizzaAppelli') }}">Visualizza Appelli</a>
          <a href="{{ url_for('teacher.visualizzaProveGestite') }}">Visualizza Prove Gestite</a>
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <div id="main" style="padding: 0px;">
          <button class="btn btn-info" onclick="openNav()">&#9776; Menu</button>
        </div>
    </nav>

    <div class="p-3 mb-2 m-5  containergrigio  d-flex justify-content-center align-items-center">
        <div class="container p-3" style="width: 75%;">

        <h2>Crea Appello</h2>
        <hr>

        <form id="appelloForm" method="POST" action="{{ url_for('teacher.creaAppello', codProva=codProva) }}">
            <div class="form-group">
                <label for="data">Data:</label>
                <input type="datetime-local" class="form-control" id="data" name="data" required>
            </div>

            <div class="form-group">
                <label for="luogo">Luogo:</label>
                <input type="text" class="form-control" id="luogo" name="luogo" required>
            </div>


            <div class="form-group">
                <label for="prova">Prova Relativa:</label>
                <select class="form-control" id="prova" name="prova" required>
                    {% for prova in prove %}
                        <option value="{{ prova.cod }}">{{ prova.cod }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-danger" onclick="creaAppello()">Crea Appello</button>
        </form>
    </div>
    </div>

    <!-- Collegamento con Bootstrap JS e Popper.js (richiesti per alcune funzionalità di Bootstrap) -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script>
    // Funzione per mostrare una notifica o eseguire azioni dopo la creazione di un appello
    function creaAppello(codiceProva) {
        // Puoi aggiungere qui la logica per creare l'appello con il codice della prova
        // e mostrare una notifica o eseguire altre azioni.
        alert('Appello creato per la prova');
    }
</script>


</body>
</html>

App/templates/teacher/visualizzaProve.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prove</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='sidebar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mystyle.css') }}">
    <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</head>
<body>

    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gestione universitaria > </a>
        <a href="{{ url_for('teacher.teacherPage') }}" class="navbar-brand">Profilo Insegnante ></a>
        <a href="{{ url_for('teacher.visualizzaCorsi') }}" class="navbar-brand">Corsi tenuti ></a>
        <a class="navbar-brand">Gestione prove</a>
        <a class="navbar-brand ml-auto"> </a>

        <div id="mySidebar" class="sidebar">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{{ url_for('teacher.visualizzaCorsi') }}">Visualizza Corsi</a>
          <a href="{{ url_for('teacher.visualizzaAppelli') }}">Visualizza Appelli</a>
          <a href="{{ url_for('teacher.visualizzaProveGestite') }}">Visualizza Prove Gestite</a>
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <div id="main" style="padding: 0px;">
          <button class="btn btn-info" onclick="openNav()">&#9776; Menu</button>
        </div>
        </a>
    </nav>

    <div class="p-3 mb-2 m-5 containergrigio">
    <div class="container p-3">

    <h2>Prove</h2>
    <hr>

    <table class="table">
        <thead class="bg-info">
            <tr>
                <th>Codice Prova</th>
                <th>Richiede</th>
                <th>Tipologia</th>
                <th>Peso</th>
                <th>Crea Appello</th>
                <th>Elimina Prova</th>
            </tr>
        </thead>
        <tbody>
            {% for prova in prove %}
                <tr>
                    <td data-prove-successive="{{ prova.getProveSuccessive(prova.cod) }}">{{ prova.cod }}</td>
                    <td>{{prova.getProvePrecedenti(prova.cod)}}</td>
                    <td>{{ prova.Tipologia }}</td>
                    <td>{{ prova.peso }}</td>
                    <td>
                        {% if prova in lista_prove_abilitate %}
                            <a href="{{ url_for('teacher.definisciAppello', codProva=prova.cod, codEsame= codEsame) }}">
                                <button type="button" class="btn btnteall">Crea Appello</button>
                            </a>
                        {% else %}
                            <button type="button" class="btn btnteall" disabled>Crea Appello</button>
                        {% endif %}
                    </td>
                    <td>
                        {% if prova in lista_prove_abilitate and not nessun_appello_relativo_all_esame %}
                        <a href="{{ url_for('teacher.eliminaProva', codProva=prova.cod, codEsame= codEsame) }}">
                            <button type="button" class="btn btn-danger">Elimina Prova</button>
                        </a>
                        {% else %}
                            <button type="button" class="btn btn-danger" disabled>Elimina Prova</button>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div id="avviso-eliminazione" class="alert alert-warning" style="display: none;">
        Attenzione, stai cercando di eliminare una prova che è primaria per le seguenti prove: <span id="prove-successive"></span>
            <br>
    Per proseguire devi prima eliminare le prove "Primarie".
    </div>
    {% if not nessun_appello_relativo_all_esame %}
    <!-- Pulsante "Definisci Nuova Prova" in basso -->
    <a href="{{ url_for('teacher.definisciProva', codEsame = codEsame) }}">
        <button type="button" class="btn btn-success mt-3">Definisci Nuova Prova</button>
    </a>
    {% else %}
        <a href="{{ url_for('teacher.definisciProva', codEsame = codEsame) }}">
        <button type="button" class="btn btn-success mt-3" disabled>Definisci Nuova Prova</button>
    </a>
    {% endif %}
    <!-- Altre informazioni dell'utente, se necessario <p class="mt-3">Benvenuto, {{ user.name }}!</p>-->
    </div>
    </div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const avvisoEliminazione = document.getElementById("avviso-eliminazione");
        const proveSuccessiveSpan = document.getElementById("prove-successive");

        const pulsantiEliminazione = document.querySelectorAll("button.btn-danger");
        pulsantiEliminazione.forEach(function(pulsante) {
            pulsante.addEventListener("click", function(event) {
                const cellaProva = this.closest("tr").querySelector("td[data-prove-successive]");
                const proveSuccessive = cellaProva.getAttribute("data-prove-successive");

                // Rimuovi le parentesi quadre dalla stringa
                const pulita = proveSuccessive.replace(/[\[\]]/g, '');
                const vuota = [' ']

                // Dividi la stringa pulita in un array utilizzando lo spazio come delimitatore
                const arrayDiValori = pulita.split(' ');
                console.log(arrayDiValori.includes(''));
                if (!arrayDiValori.includes('')) {

                    avvisoEliminazione.style.display = "block";
                    proveSuccessiveSpan.textContent = arrayDiValori + "proveSuccessive.length > 0?" + arrayDiValori;

                    event.preventDefault();
                }
            });
        });
    });
</script>


</body>
</html>