App/blueprints/auth.py
import os

from flask import Blueprint, redirect, url_for, session, request, render_template, current_app
from flask_login import login_required, current_user, login_user, logout_user

from App.db.models.database import Docenti, Studenti, db, Admin
from App.utils.utilies import check_credentials

auth = Blueprint('auth', __name__)


@auth.route('/')
def home():
    print("sono in home")
    db.session.close()
    current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_UTENTE')
    return render_template('home.html')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if session['user_type'] == Studenti.__name__:
            return redirect(url_for('student.studentPage'))
        if session['user_type'] == Admin.__name__:
            return redirect(url_for('admin.adminPage'))
        elif session['user_type'] == Docenti.__name__:
            return redirect(url_for('teacher.teacherPage'))

    db.session.close()
    current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_UTENTE')
    print(current_app.config['SQLALCHEMY_DATABASE_URI'])
    if request.method == 'POST':
        print("request.form['user']:", request.form['user'])
        pair = check_credentials(request.form['user'], request.form['password'])
        print("pair:", pair)
        if pair[0]:
            print('login success')
            login_user(pair[1])
            db.session.close()
            if session['user_type'] == Studenti.__name__:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_STUDENTE')
                return redirect(url_for('student.studentPage'))
            if session['user_type'] == Admin.__name__:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_ADMIN')
                return redirect(url_for('admin.adminPage'))
            else:
                current_app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL_LOCALE_DOCENTE')
                return redirect(url_for('teacher.teacherPage'))

    print('login failed')
    return render_template('login.html')


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

App/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Errore</title>
    <!-- Aggiungi il link al file CSS di Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-danger text-white">
                        <h4>Errore</h4>
                    </div>
                    <div class="card-body">
                        <!-- Usa Jinja per inserire il messaggio di errore dinamicamente -->
                        <p>{{ error }}</p>
                    </div>
                    <div class="card-footer text-center">
                        <a href="{{ url_for('auth.home') }}" class="btn btn-primary">Torna alla Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Aggiungi il link al file JavaScript di Bootstrap (opzionale, ma consigliato) -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

App/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <!-- Link ai file CSS di Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            padding: 80px 0;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
        Gestione università
        </a>
    </nav>

    <div class="container">
        <div class="jumbotron text-center">
            <h1 class="display-4">Benvenuto alla Home</h1>
            <p class="lead">Clicca il bottone qui sotto per accedere alla pagina di login.</p>
            <hr class="my-4">
            <p>Se hai gia effettuato il login verrai reindirizzato alla tua area personale</p>
            <!-- Bottone per la pagina di login -->
            <a class="btn btn-danger btn" href="/login" role="button">Login</a>
        </div>
    </div>

    <!-- Link ai file JavaScript

App/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Home page per il login</title>
    <style>
        .containergrigio {
            background-color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            padding: 20px;
            margin-top: 50px;
        }
    </style>
  </head>

  <body>
    
    <nav class="navbar navbar-dark bg-info">
        <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='graduation-cap-png.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
        Gestione università
        </a>
    </nav>

    <div class="p-3 mb-2 m-5  bg-light text-dark containergrigio">

    <div class="container my-5 text-center border w-25 p-3">
        <h3>Accedi</h3>
        <form action="/login" method="POST">
            <div class="form-group row">
              <label for="inputEmail3" class="col-sm-3 col-form-label">Email</label>
              <div class="col-sm-9">
                <input  name="user" type="email" class="form-control" id="inputEmail3">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputPassword3" class="col-sm-3 col-form-label">Password</label>
              <div class="col-sm-9">
                <input  name="password" type="password" class="form-control" id="inputPassword3">
              </div>
            </div>

            <button type="submit" class="btn btn-danger">Login</button>
          </form>
      </div>
   
    </div>
    <hr>
    <footer class="fixed-bottom" style="background-color: #cccccc; color: black; padding: 10px;">
          <div class="container">
              <div class="row justify-content-center">
                  <h5>About us</h5>
              </div>
              <div class="row justify-content-center">
                    <p><i>Powered by: Eleonora Greco, Domenico Sosta, Donald Gera</i></p>
              </div>
          </div>
    </footer>

  </body>
</html>